spring.application.name=projetoDTO
# Force o dialeto para evitar o erro de detec��o
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Verifique se a URL aponta para "db" (nome do servi�o no docker-compose)
spring.datasource.url=jdbc:mysql://localhost:3306/dto_revisao
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Ajuda a debugar a conex�o
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update